<?php

module_load_include('inc', 'imgix', 'imgix');

/**
 * Implements hook_menu().
 */
function imgix_menu() {
  $items['admin/config/services/imgix'] = array(
    'title' => t('Imgix'),
    'description' => t('Administration page to setup Imgix integration.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('imgix_admin'),
    'access arguments' => array('administer imgix settings'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'imgix.admin.inc'
  );

  return $items;
}
