<?php

use Drupal\Core\Render\Element;

function imgix_theme($existing, $type, $theme, $path)
{
    return [
        'imgix_image' => [
            'template' => 'imgix-image',
            'variables' => [
                'preset' => null,
                'url' => null,
                'linkUrl' => null,
                'title' => null,
                'caption' => null,
            ],
        ],
    ];
}
