<?php

use Drupal\imgix\Entity\ImgixImageStyle;
use Drupal\imgix\Plugin\ImageEffect\ScaleAndCropImageEffect;

/**
 * Implements @see hook_entity_type_alter().
 */
function imgix_entity_type_alter(array &$entity_types)
{
    if (isset($entity_types['image_style'])) {
        $entity_types['image_style']->setClass(ImgixImageStyle::class);
    }
}

/**
 * Implements @see hook_image_effect_info_alter().
 */
function imgix_image_effect_info_alter(array &$effects): void
{
    if (isset($effects['image_scale_and_crop'])) {
        $effects['image_scale_and_crop']['class'] = ScaleAndCropImageEffect::class;
    }
}
