imgix.settings:
  type: config_object
  label: 'Imgix settings'
  mapping:
    settings:
      type: mapping
      mapping:
        source_domain:
          label: 'Domain'
          type: string
        mapping_type:
          label: 'Source type'
          type: string
        s3_has_prefix:
          label: 'S3 bucket has prefix'
          type: boolean
        mapping_url:
          label: 'Base URL'
          type: string
        secure_url_token:
          label: 'Secure URL Token'
          type: string
        https:
          label: 'HTTPS support'
          type: boolean
        external_cdn:
          label: 'External CDN'
          type: string

imgix.presets:
  type: config_object
  label: 'Imgix presets'
  mapping:
    presets:
      type: sequence
      label: 'List of presets'
      sequence:
        type: mapping
        label: 'Preset'
        mapping:
          key:
            type: string
            label: 'The actual key'
          query:
            type: text
            label: 'The query string for this key'
