imgix.settings:
  type: config_object
  label: 'Imgix settings'
  mapping:
    settings:
      type: mapping
      mapping:
        source_domain:
          label: 'Source domain'
          description: 'The Imgix domain from which your images are served. Usually, this is a subdomain of imgix.net.'
          type: string
        external_cdn:
          label: 'External CDN'
          description: 'The domain of an external CDN through which the images should be served, instead of the source domain.'
          type: string
        mapping_type:
          label: 'Mapping type'
          description: 'The way Imgix connects to your image storage.'
          type: string
        secure_url_token:
          label: 'Secure URL Token'
          description: 'Signing URLs using a token prevents unauthorized parties from changing the parameters.'
          type: string
        s3_has_prefix:
          label: 'S3 bucket has prefix'
          description: 'If this option is enabled, the first part of the image path will be removed. This can be useful in case your images are stored in a subfolder of the S3 bucket.'
          type: boolean
        https:
          label: 'HTTPS support'
          type: boolean
